class ConstantVariables {
  static const String google = "Google";
  static const String phone = "Phone";
  static const String logOut = "Log out";
  static const String orderSummary = "Order Summary";
  static const String placeOrder = "Place Order";
  static const String saladsAndSoup = "Salads and Soup";
  static const String fromTheBranyard = "From The Barnyard";
  static const String fromTheHenHouse = 'From the Hen House';
  static const String freshFromTheSea = 'Fresh From The Sea';
  static const String biryani = "Biryani";
  static const String fastFood = "Fast Food";
  static const String enterYourNumber = 'Enter Your Number';
  static const String getOTP = 'Enter your OTP';
  static const String invalidNumber = 'Invalid Number';
  static const String invalidOtp = 'Invalid OTP';
  static const String getOtpButton = 'Get OTP';
  static const String submit = "Submit";
  static const String confirm = "Confirm";
  static const String cancel = "Cancel";
  static const String confirmationText = "Are you sure you need to Logout?";
  static const String alert = "Alert";
  static const String orderPlaced = 'Your order has been placed Successfully';
  static const String customization = "Customization Available";
  static const String noItem = "No Items in your Cart";
  static const String continueShopping = "Like to Order more !!";
  static const String totalAmount = "Total Amount";
  //static const String apiLink =
}
